// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_ScreenTimerSetting = NULL;
lv_obj_t * ui_LabelConfigTimerValue = NULL;
lv_obj_t * ui_ContainerTimerHeader = NULL;
lv_obj_t * ui_LabelTimerTitle = NULL;
lv_obj_t * ui_ArcTimeValue = NULL;
lv_obj_t * ui_Label2 = NULL;
// event funtions

// build funtions

void ui_ScreenTimerSetting_screen_init(void)
{
    ui_ScreenTimerSetting = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenTimerSetting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenTimerSetting, lv_color_hex(0xFFEDFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenTimerSetting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelConfigTimerValue = lv_label_create(ui_ScreenTimerSetting);
    lv_obj_set_width(ui_LabelConfigTimerValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelConfigTimerValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelConfigTimerValue, 0);
    lv_obj_set_y(ui_LabelConfigTimerValue, 13);
    lv_obj_set_align(ui_LabelConfigTimerValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelConfigTimerValue, "05:00");
    lv_obj_set_style_text_font(ui_LabelConfigTimerValue, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerTimerHeader = lv_obj_create(ui_ScreenTimerSetting);
    lv_obj_remove_style_all(ui_ContainerTimerHeader);
    lv_obj_set_width(ui_ContainerTimerHeader, 280);
    lv_obj_set_height(ui_ContainerTimerHeader, 35);
    lv_obj_set_align(ui_ContainerTimerHeader, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_ContainerTimerHeader, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ContainerTimerHeader, lv_color_hex(0xF681FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerTimerHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTimerTitle = lv_label_create(ui_ContainerTimerHeader);
    lv_obj_set_width(ui_LabelTimerTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTimerTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTimerTitle, -4);
    lv_obj_set_y(ui_LabelTimerTitle, 0);
    lv_obj_set_align(ui_LabelTimerTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTimerTitle, "CZAS PRACY");
    lv_obj_set_style_text_color(ui_LabelTimerTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTimerTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTimerTitle, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcTimeValue = lv_arc_create(ui_ScreenTimerSetting);
    lv_obj_set_width(ui_ArcTimeValue, 200);
    lv_obj_set_height(ui_ArcTimeValue, 200);
    lv_obj_set_x(ui_ArcTimeValue, 0);
    lv_obj_set_y(ui_ArcTimeValue, 24);
    lv_obj_set_align(ui_ArcTimeValue, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_ArcTimeValue, 50);
    lv_obj_set_style_arc_width(ui_ArcTimeValue, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcTimeValue, lv_color_hex(0xF681FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcTimeValue, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcTimeValue, 15, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcTimeValue, lv_color_hex(0xF669FF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcTimeValue, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_ScreenTimerSetting);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 0);
    lv_obj_set_y(ui_Label2, 43);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "mm:ss");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xF681FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_ScreenTimerSetting_screen_destroy(void)
{
    if(ui_ScreenTimerSetting) lv_obj_del(ui_ScreenTimerSetting);

    // NULL screen variables
    ui_ScreenTimerSetting = NULL;
    ui_LabelConfigTimerValue = NULL;
    ui_ContainerTimerHeader = NULL;
    ui_LabelTimerTitle = NULL;
    ui_ArcTimeValue = NULL;
    ui_Label2 = NULL;

}
