// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_ScreenMain = NULL;
lv_obj_t * ui_ContainerMainHeader = NULL;
lv_obj_t * ui_LabelMainTitle = NULL;
lv_obj_t * ui_ArcMainTimerValue = NULL;
lv_obj_t * ui_LabelMainTimerValue = NULL;
lv_obj_t * ui_LabelPowerValueSet = NULL;
// event funtions

// build funtions

void ui_ScreenMain_screen_init(void)
{
    ui_ScreenMain = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenMain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenMain, lv_color_hex(0xFFEDFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenMain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerMainHeader = lv_obj_create(ui_ScreenMain);
    lv_obj_remove_style_all(ui_ContainerMainHeader);
    lv_obj_set_width(ui_ContainerMainHeader, 240);
    lv_obj_set_height(ui_ContainerMainHeader, 35);
    lv_obj_set_align(ui_ContainerMainHeader, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_ContainerMainHeader, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ContainerMainHeader, lv_color_hex(0xF681FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerMainHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMainTitle = lv_label_create(ui_ContainerMainHeader);
    lv_obj_set_width(ui_LabelMainTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMainTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelMainTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMainTitle, "PRACA");
    lv_obj_set_style_text_color(ui_LabelMainTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMainTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMainTitle, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcMainTimerValue = lv_arc_create(ui_ScreenMain);
    lv_obj_set_width(ui_ArcMainTimerValue, 200);
    lv_obj_set_height(ui_ArcMainTimerValue, 200);
    lv_obj_set_x(ui_ArcMainTimerValue, 0);
    lv_obj_set_y(ui_ArcMainTimerValue, 24);
    lv_obj_set_align(ui_ArcMainTimerValue, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_ArcMainTimerValue, 50);
    lv_obj_set_style_arc_width(ui_ArcMainTimerValue, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcMainTimerValue, lv_color_hex(0xF681FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcMainTimerValue, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcMainTimerValue, 15, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcMainTimerValue, lv_color_hex(0xF669FF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcMainTimerValue, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelMainTimerValue = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_LabelMainTimerValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMainTimerValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMainTimerValue, 0);
    lv_obj_set_y(ui_LabelMainTimerValue, 13);
    lv_obj_set_align(ui_LabelMainTimerValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMainTimerValue, "05:00");
    lv_obj_set_style_text_font(ui_LabelMainTimerValue, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPowerValueSet = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_LabelPowerValueSet, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPowerValueSet, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPowerValueSet, 0);
    lv_obj_set_y(ui_LabelPowerValueSet, 43);
    lv_obj_set_align(ui_LabelPowerValueSet, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPowerValueSet, "50%");
    lv_obj_set_style_text_color(ui_LabelPowerValueSet, lv_color_hex(0xF681FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPowerValueSet, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_ScreenMain_screen_destroy(void)
{
    if(ui_ScreenMain) lv_obj_del(ui_ScreenMain);

    // NULL screen variables
    ui_ScreenMain = NULL;
    ui_ContainerMainHeader = NULL;
    ui_LabelMainTitle = NULL;
    ui_ArcMainTimerValue = NULL;
    ui_LabelMainTimerValue = NULL;
    ui_LabelPowerValueSet = NULL;

}
