// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREENPOWERSETTING_H
#define UI_SCREENPOWERSETTING_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenPowerSetting
extern void ui_ScreenPowerSetting_screen_init(void);
extern void ui_ScreenPowerSetting_screen_destroy(void);
extern lv_obj_t * ui_ScreenPowerSetting;
extern lv_obj_t * ui_ArcPowerValue;
extern lv_obj_t * ui_LabelPowerValue;
extern lv_obj_t * ui_ContainerPowerHeader;
extern lv_obj_t * ui_LabelPowerTitle;
extern lv_obj_t * ui_Label3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

