// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREENTIMERSETTING_H
#define UI_SCREENTIMERSETTING_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenTimerSetting
extern void ui_ScreenTimerSetting_screen_init(void);
extern void ui_ScreenTimerSetting_screen_destroy(void);
extern lv_obj_t * ui_ScreenTimerSetting;
extern lv_obj_t * ui_LabelConfigTimerValue;
extern lv_obj_t * ui_ContainerTimerHeader;
extern lv_obj_t * ui_LabelTimerTitle;
extern lv_obj_t * ui_ArcTimeValue;
extern lv_obj_t * ui_Label2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

