// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_ScreenPowerSetting = NULL;
lv_obj_t * ui_ArcPowerValue = NULL;
lv_obj_t * ui_LabelPowerValue = NULL;
lv_obj_t * ui_ContainerPowerHeader = NULL;
lv_obj_t * ui_LabelPowerTitle = NULL;
lv_obj_t * ui_Label3 = NULL;
// event funtions

// build funtions

void ui_ScreenPowerSetting_screen_init(void)
{
    ui_ScreenPowerSetting = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenPowerSetting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenPowerSetting, lv_color_hex(0xFFEDFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenPowerSetting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcPowerValue = lv_arc_create(ui_ScreenPowerSetting);
    lv_obj_set_width(ui_ArcPowerValue, 200);
    lv_obj_set_height(ui_ArcPowerValue, 200);
    lv_obj_set_x(ui_ArcPowerValue, 0);
    lv_obj_set_y(ui_ArcPowerValue, 24);
    lv_obj_set_align(ui_ArcPowerValue, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_ArcPowerValue, 50);
    lv_obj_set_style_arc_width(ui_ArcPowerValue, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_shadow_width(ui_ArcPowerValue, 50, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ArcPowerValue, 50, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_ArcPowerValue, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_ArcPowerValue, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_ArcPowerValue, lv_color_hex(0xF781FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcPowerValue, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcPowerValue, 15, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcPowerValue, lv_color_hex(0xF46BFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcPowerValue, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelPowerValue = lv_label_create(ui_ScreenPowerSetting);
    lv_obj_set_width(ui_LabelPowerValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPowerValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPowerValue, 0);
    lv_obj_set_y(ui_LabelPowerValue, 13);
    lv_obj_set_align(ui_LabelPowerValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPowerValue, "50");
    lv_obj_set_style_text_font(ui_LabelPowerValue, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerPowerHeader = lv_obj_create(ui_ScreenPowerSetting);
    lv_obj_remove_style_all(ui_ContainerPowerHeader);
    lv_obj_set_width(ui_ContainerPowerHeader, 240);
    lv_obj_set_height(ui_ContainerPowerHeader, 35);
    lv_obj_set_align(ui_ContainerPowerHeader, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_ContainerPowerHeader, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ContainerPowerHeader, lv_color_hex(0xF681FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerPowerHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPowerTitle = lv_label_create(ui_ContainerPowerHeader);
    lv_obj_set_width(ui_LabelPowerTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPowerTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPowerTitle, -4);
    lv_obj_set_y(ui_LabelPowerTitle, 0);
    lv_obj_set_align(ui_LabelPowerTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPowerTitle, "MOC LAMPY");
    lv_obj_set_style_text_color(ui_LabelPowerTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPowerTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPowerTitle, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_ScreenPowerSetting);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 0);
    lv_obj_set_y(ui_Label3, 43);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "%");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xF681FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_ScreenPowerSetting_screen_destroy(void)
{
    if(ui_ScreenPowerSetting) lv_obj_del(ui_ScreenPowerSetting);

    // NULL screen variables
    ui_ScreenPowerSetting = NULL;
    ui_ArcPowerValue = NULL;
    ui_LabelPowerValue = NULL;
    ui_ContainerPowerHeader = NULL;
    ui_LabelPowerTitle = NULL;
    ui_Label3 = NULL;

}
